#!/bin/bash
dir=$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)

mkdir -p config app cache bundles
rm -f bootstrap.php

phpenv config-add $dir/config/$TRAVIS_PHP_VERSION.ini
phpenv config-add $dir/config/apc.ini

echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
