#!/bin/bash
dir=$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)
$dir/install-cssmin
$dir/install-yaml

travis_retry composer install
travis_retry composer require "satooshi/php-coveralls" "^1" --dev --no-update
